import { RiFacebookFill } from "react-icons/ri";
import { IoLogoTwitter } from "react-icons/io";
import { AiFillInstagram } from "react-icons/ai";
import { FcAndroidOs } from "react-icons/fc";
import { FaApple } from "react-icons/fa";
import { ImLink } from "react-icons/im";
import { FaUserAlt } from "react-icons/fa";
import { SiPinboard } from "react-icons/si";
import { GiExpand } from "react-icons/gi";
export const lazy = [
  {
    title: "About Us",
    titleLink: "/Aboutus",
  },
  { title: "Stores", titleLink: "/Stores" },
  { title: "Wine Stores", titleLink: "/Winestores" },
  { title: "Beer Stores", titleLink: "/Beerstores" },
  { title: "Alcohol Delivery", titleLink: "/Alcoholdelivery" },
];
export const help = [
  { title: "In Store Pickup", titleLink: "/Storepick" },
  { title: "FAQ", titleLink: "/FAQ" },
  { title: "Contact Us", titleLink: "/Contactus" },
  { title: "Request Product", titleLink: "/Request" },
  { title: "Return & Refund", titleLink: "/Refund" },
  { title: "Join as Retailer", titleLink: "/Join" },
];
export const account = [
  { title: "Sign In", titleLink: "/Signin" },
  { title: "Sign Up", titleLink: "/Singup" },
  { title: "Forgot Password?", titleLink: "/Pass" },
];
export const social = [
  {
    title: <RiFacebookFill />,
    titleLink: "https://web.facebook.com/?_rdc=1&_rdr",
  },
  {
    title: <IoLogoTwitter />,
    titleLink:
      "https://www.google.com/search?channel=fs&client=ubuntu&q=twitter+login",
  },
  { title: <AiFillInstagram />, titleLink: "https://www.instagram.com/" },
];
export const down = [
  { title: <FcAndroidOs />, titleLink: "https://play.google.com/store/games" },
  { title: <FaApple />, titleLink: "https://www.apple.com/app-store/" },
];
export const pay = [
  { title: "./assets/kcb.png" },
  { title: "./assets/equity.jpg" },
  { title: "./assets/Platinum.png" },
  { title: "./assets/rename.jpeg" },
  { title: "./assets/visa.png" },
];
export const city = [
  {
    title: "Nairobi",
    description: "18 locations",
    loc1: "Brookside",
    link1: "/Brookside",
    loc2: "Buru buru",
    link2: "/Buru buru",
    loc3: "Dagoretti",
    link3: "/Dagoretti",
    loc4: "Embakasi",
    link4: "/Embakasi",
    loc5: "Hurlingham",
    link5: "/Hurlingham",
    loc6: "Kabete",
    link6: "/Kabete",
    loc7: "Kayole",
    link7: "/Kayole",
    loc8: "Kinoo",
    link8: "/Kinoo",
    loc9: "Lavington",
    link9: "/Lavington",
    loc10: "Loresho",
    link10: "/Loresho",
    loc11: "Muthaiga",
    link11: "/Muthaiga",
    loc12: "Nairobi west",
    link12: "/Nairobi west",
    loc13: "Ngara",
    link13: "/Ngara",
    loc14: "Ngummo",
    link14: "/Ngummo",
    loc15: "Savannah",
    link15: "/Savannah",
    loc16: "Thome",
    link16: "/Thome",
    loc17: "Uthiru",
    link17: "/Uthiru",
    loc18: "Yaya Centre",
    link18: "/Yaya",
  },
  {
    title: "Kisumu",
    description: "11 locations",
    loc1: "Kondele",
    link1: "/Kondele",
    loc2: "Manyatta",
    link2: "/Manyatta",
    loc3: "Tom Mboya",
    link3: "/Tom Mboya",
    loc4: "Polyview",
    link4: "/Polyview",
    loc5: "Nyalenda",
    link5: "/Nyalenda",
    loc6: "Migosi",
    link6: "/Migosi",
    loc7: "Nyamasaria",
    link7: "/Nyamasaria",
    loc8: "Riat",
    link8: "/Riat",
    loc9: "Milimani",
    link9: "/Milimani",
    loc10: "Okore",
    link10: "/Okore",
    loc11: "Mamboleo",
    link11: "/Mamboleo",
  },
  {
    title: "Mombasa",
    description: "11 locations",
    loc1: "Kondele",
    link1: "/Kondele",
    loc2: "Manyatta",
    link2: "/Manyatta",
    loc3: "Tom Mboya",
    link3: "/Tom Mboya",
    loc4: "Polyview",
    link4: "/Polyview",
    loc5: "Nyalenda",
    link5: "/Nyalenda",
    loc6: "Migosi",
    link6: "/Migosi",
    loc7: "Nyamasaria",
    link7: "/Nyamasaria",
    loc8: "Riat",
    link8: "/Riat",
    loc9: "Milimani",
    link9: "/Milimani",
    loc10: "Okore",
    link10: "/Okore",
    loc11: "Mamboleo",
    link11: "/Mamboleo",
  },
  {
    title: "Nakuru",
    description: "11 locations",
    loc1: "Freehold",
    link1: "/Freehold",
    loc2: "Kiamunyi",
    link2: "/Kiamunyi",
    loc3: "Mawanga",
    link3: "/Mawanga",
    loc4: "Mwariki",
    link4: "/Mwariki",
    loc5: "Pipeline",
    link5: "/Pipeline",
    loc6: "Pangani.",
    link6: "/Pangani.",
    loc7: "NNgata",
    link7: "/Ngata",
    loc8: "Bondeni",
    link8: "/Bondeni",
    loc9: "Lanet",
    link9: "/Lanet",
    loc10: "Bahati ",
    link10: "/Bahati ",
    loc11: "Racecourse",
    link11: "/Racecourse",
  },
  {
    title: "Thika",
    description: "12 locations",
    loc1: "Kisii Estate",
    link1: "/Kisii Estate",
    loc2: "Runda Estate",
    link2: "/Runda Estate",
    loc3: "Chania Gardens Estate",
    link3: "/Chania Gardens Estate",
    loc4: "View Lands Estate",
    link4: "/View Lands Estate",
    loc5: "Gathiru Estate",
    link5: "/Gathiru Estate",
    loc6: "Starehe Estate",
    link6: "/Starehe Estate",
    loc7: "Kiboko Estate",
    link7: "Kiboko Estate",
    loc8: "Landless",
    link8: "/Landless",
    loc9: "Kiandutu estate",
    link9: "/Kiandutu estate",
    loc10: "Muthaiga Estate ",
    link10: "/Muthaiga Estate ",
    loc11: "Kiganjo Estate",
    link11: "/Kiganjo Estate",
  },
  {
    title: "Eldoret",
    description: "12 locations",
    loc1: "Elgon View",
    link1: "/Elgon View",
    loc2: "Pioneer estate",
    link2: "/Pioneer estate",
    loc3: "Kapsoya",
    link3: "/Kapsoya",
    loc4: "West Indies",
    link4: "/West Indies",
    loc5: "Langas",
    link5: "/Langas",
    loc6: "Mwanzo estate",
    link6: "/Mwanzo estate",
    loc7: "Action estate",
    link7: "Action estate",
    loc8: "Huruma estate",
    link8: "/Huruma estate",
    loc9: "Annex estate",
    link9: "/Annex estate",
    loc10: "Kamukunji estate ",
    link10: "Kamukunji estate",
    loc11: "Maili nne",
    link11: "/Maili nne",
  },
  {
    title: "Kitale",
    description: "12 locations",
    loc1: "Elgon View",
    link1: "/Elgon View",
    loc2: "Pioneer estate",
    link2: "/Pioneer estate",
    loc3: "Kapsoya",
    link3: "/Kapsoya",
    loc4: "West Indies",
    link4: "/West Indies",
    loc5: "Langas",
    link5: "/Langas",
    loc6: "Mwanzo estate",
    link6: "/Mwanzo estate",
    loc7: "Action estate",
    link7: "Action estate",
    loc8: "Huruma estate",
    link8: "/Huruma estate",
    loc9: "Annex estate",
    link9: "/Annex estate",
    loc10: "Kamukunji estate ",
    link10: "Kamukunji estate",
    loc11: "Maili nne",
    link11: "/Maili nne",
  },
  {
    title: "Kisii",
    description: "12 locations",
    loc1: "Elgon View",
    link1: "/Elgon View",
    loc2: "Pioneer estate",
    link2: "/Pioneer estate",
    loc3: "Kapsoya",
    link3: "/Kapsoya",
    loc4: "West Indies",
    link4: "/West Indies",
    loc5: "Langas",
    link5: "/Langas",
    loc6: "Mwanzo estate",
    link6: "/Mwanzo estate",
    loc7: "Action estate",
    link7: "Action estate",
    loc8: "Huruma estate",
    link8: "/Huruma estate",
    loc9: "Annex estate",
    link9: "/Annex estate",
    loc10: "Kamukunji estate ",
    link10: "Kamukunji estate",
    loc11: "Maili nne",
    link11: "/Maili nne",
  },
];
export const retail = [
  {
    title: "Boost Your Sales",
    titlePar:
      "On our platform, you can sell your alcoholic beverages and expand your consumer base to increase sales.",
    titleIcon: <ImLink />,
  },
  {
    title: "Attract New Clients",
    titlePar: "Get new clients in your area with an online presence.",
    titleIcon: <FaUserAlt />,
  },
  {
    title: "Gain knowledge",
    titlePar:
      "To better understand business performance, access to dashboards, reports, and analytics.",
    titleIcon: <SiPinboard />,
  },
  {
    title: "Expand Online",
    titlePar:
      "Let us handle your online orders while assisting you in expanding your company.",
    titleIcon: <GiExpand />,
  },
];
